# IR 11. 문법 정리1(데이터형, 형변환, 행렬, 배열)
> "작성완료"

- toc:true
- branch: master
- badges: true
- comments: true
- [R]

---
# Introduce R 
- lecture: Introduce R_8-1nd week of lectures
- lecture date: 2021-10-28
- lecturer: Guebin choi
- study date: 2022-02-22
- author: Kione kim
---

In [ ]:
#hide
options(jupyter.plot_scale=3)
options(jupyter.display_mimetypes=c("text/html"))
options(jupyter.rich_display=FALSE)
options(repr.plot.width=6,repr.plot.height=6,repr.plot.res=300)
options(max.print=1000)

## 문법 정리1

### 데이터형
`-` R에서 데이터를 구성하는 네가지 기본형

`-` 수치형(numeric): 정수, 실수, 지수 등을 나타내며 실수가 기본형

In [ ]:
a=345
mode(a)

[1] "numeric"

In [ ]:
a=34.55
mode(a)

[1] "numeric"

`-` 논리형(logical): 논리적 참과 거짓을 나타낸다.

In [ ]:
a=T
mode(a)

[1] "logical"

In [ ]:
a=TRUE
mode(a)

[1] "logical"

In [ ]:
a=F
mode(a)

[1] "logical"

In [ ]:
a=FALSE
mode(a)

[1] "logical"

`-` 문자형

In [ ]:
a='answk'
mode(a)

[1] "character"

In [ ]:
a='TRUE'
mode(a)

[1] "character"

In [ ]:
a='1'
mode(a)

[1] "character"

In [ ]:
a="FALSE"
mode(a)

[1] "character"

`-` 참고:storage.mode()

In [ ]:
a=pi
a

[1] 3.141593

In [ ]:
mode(a)

[1] "numeric"

In [ ]:
storage.mode(a)

[1] "double"

In [ ]:
a=1:2
a

[1] 1 2

In [ ]:
storage.mode(a)

[1] "integer"

### 형변환

#### 방법1

In [ ]:
a='132'
mode(a)

[1] "character"

`-` 이것을 수치형(numeric)으로 바꾸고 싶다.

In [ ]:
mode(a) <- "numeric"

In [ ]:
a

[1] 132

#### 방법2

In [ ]:
a= "1234"
mode(a)

[1] "character"

In [ ]:
a

[1] "1234"

In [ ]:
as.numeric(a)

[1] 1234

#### 예제

##### 예제1: logical -> numeric

In [ ]:
a=F
a

[1] FALSE

In [ ]:
as.numeric(a)

[1] 0

##### 예제2: numeric -> logical

In [ ]:
a=1
a

[1] 1

In [ ]:
as.logical(a)

[1] TRUE

In [ ]:
a=0
a

[1] 0

In [ ]:
as.logical(a)

[1] FALSE

`-` 그럼 0,1 이외에 숫자를 넣으면 어떻게 될까?

In [ ]:
a=2
a

[1] 2

In [ ]:
as.logical(a)

[1] TRUE

In [ ]:
a=-1
a

[1] -1

In [ ]:
as.logical(a)

[1] TRUE

In [ ]:
a=3.33
a

[1] 3.33

In [ ]:
as.logical(a)

[1] TRUE

- 0만 FALSE로 반환하고 나머지 모두는 TRUE로 반환한다.

##### 예제3

In [ ]:
a='asdhflk'
a=as.numeric(a)

Warning message in eval(expr, envir, enclos):
"강제형변환에 의해 생성된 NA 입니다"


In [ ]:
a

[1] NA

In [ ]:
mode(a)

[1] "numeric"

In [ ]:
a='adjsfi'
a=as.logical(a)

In [ ]:
a

[1] NA

In [ ]:
mode(a)

[1] "logical"

`-` 모드가 서로 다른 원소로 이루어진 벡터의 mode는 무엇일까?

`-` 예시1

In [ ]:
a <- c(1,T,'1')

In [ ]:
mode(a)

[1] "character"

`-` 예시2

In [ ]:
a <- c(1,T)

In [ ]:
mode(a)

[1] "numeric"

- 서로 다른 기본형을 가지는 원소로 벡터를 만들면 한 가지 형으로 자동 형 변환이 된다.

### 행렬

`-` 행렬도 벡터와 같이 동일한 형의 원소로 구성된다.

#### 행렬의 속성

In [ ]:
A = cbind(c(1,2,3,4),c(2,4,6,8),c(7,8,9,10))
A

     [,1] [,2] [,3]
[1,] 1    2     7  
[2,] 2    4     8  
[3,] 3    6     9  
[4,] 4    8    10  

In [ ]:
length(A)

[1] 12

In [ ]:
mode(A)

[1] "numeric"

In [ ]:
dim(A)

[1] 4 3

In [ ]:
dim(A) <- c(3,4)

In [ ]:
dim(A)

[1] 3 4

In [ ]:
dimnames(A)

NULL

`-` 지금은 이름이 없지만 아래와 같이 이름이 있을 수 있다.

In [ ]:
x <- c(1,2,3,4)
y <- c(3,5,7,9)
z <- c(7,8,9,10)
A <- cbind(x,y,z)
A

     x y z 
[1,] 1 3  7
[2,] 2 5  8
[3,] 3 7  9
[4,] 4 9 10

In [ ]:
dimnames(A)

[[1]]
NULL

[[2]]
[1] "x" "y" "z"


In [ ]:
A <- rbind(x,y,z)
A

  [,1] [,2] [,3] [,4]
x 1    2    3     4  
y 3    5    7     9  
z 7    8    9    10  

In [ ]:
dimnames(A)

[[1]]
[1] "x" "y" "z"

[[2]]
NULL


#### 매트릭스를 만드는 방법

##### 방법1: matrix 함수를 이용하는 방법

`-` 예제1

In [ ]:
matrix(1:8,ncol=2)

     [,1] [,2]
[1,] 1    5   
[2,] 2    6   
[3,] 3    7   
[4,] 4    8   

In [ ]:
matrix(1:8,ncol=2,byrow = T)

     [,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 5    6   
[4,] 7    8   

- `byrow = T` 옵션을 사용하면 컬럼기준으로 원소를 입력하는 것이 아닌 row기준으로 원소를 입력해준다.

`-` 예제2

In [ ]:
matrix(1:9,ncol=3)

     [,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9   

In [ ]:
matrix(1:7,ncol=3)

Warning message in matrix(1:7, ncol = 3):
"데이터의 길이[7]가 행의 개수[3]의 배수가 되지 않습니다"


     [,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    1   
[3,] 3    6    2   

`-` 예제3

In [ ]:
matrix(1:8,nrow=2)

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8   

- $1$행에 $(1,2,3,4)$, $2$행에 $(5,6,7,8)$ 입력되는 것이 아닌 컬럼기준으로 입력이 되어 기대한 것과 다른 값이 나온다

- 이는 다음과 같이 `byrow = T` 옵션을 통해 row기준으로 입력할 수 있다.

In [ ]:
matrix(1:8,nrow=2,byrow = T)

     [,1] [,2] [,3] [,4]
[1,] 1    2    3    4   
[2,] 5    6    7    8   

`-` 예제4

In [ ]:
matrix(1:9,nrow=3)

     [,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9   

In [ ]:
matrix(1:10,nrow=3)

Warning message in matrix(1:10, nrow = 3):
"데이터의 길이[10]가 행의 개수[3]의 배수가 되지 않습니다"


     [,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8     1  
[3,] 3    6    9     2  

`-` 예제5

In [ ]:
matrix(1:10)

      [,1]
 [1,]  1  
 [2,]  2  
 [3,]  3  
 [4,]  4  
 [5,]  5  
 [6,]  6  
 [7,]  7  
 [8,]  8  
 [9,]  9  
[10,] 10  

- 입력이 없으면 한 컬럼에 대해 입력하게 된다

##### 방법2: rbind 함수를 이용하는 방법

`-` 예제1

In [ ]:
rbind(1:6,rep(c(1,2),3))

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    2    3    4    5    6   
[2,] 1    2    1    2    1    2   

`-` 예제2

In [ ]:
rbind(1:5,5:1,1:3)

Warning message in rbind(1:5, 5:1, 1:3):
"number of columns of result is not a multiple of vector length (arg 3)"


     [,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4    5   
[2,] 5    4    3    2    1   
[3,] 1    2    3    1    2   

- python이었다면 오류가 났을 것이지만, R에서는 경고메시지 정도만 뜨고 알아서 채워준다.

In [ ]:
rbind(1:4,4:1,1:2)

     [,1] [,2] [,3] [,4]
[1,] 1    2    3    4   
[2,] 4    3    2    1   
[3,] 1    2    1    2   

- 경고메시지도 뜨지 않는다. $1,2$가 두 번씩 자동으로 입력되었다.

In [ ]:
rbind(1:4,4:1,rep(1:2,2))

     [,1] [,2] [,3] [,4]
[1,] 1    2    3    4   
[2,] 4    3    2    1   
[3,] 1    2    1    2   

- 위의 결과를 나타내는 정석적인 코드는 위와 같음

`-` 예제3: 행에 이름 넣기

In [ ]:
rbind("row1"=1:6,"row2"=6:1,"row3"=1:3)

     [,1] [,2] [,3] [,4] [,5] [,6]
row1 1    2    3    4    5    6   
row2 6    5    4    3    2    1   
row3 1    2    3    1    2    3   

##### 방법3: cbind 함수를 이용하는 방법

`-` 예제1

In [ ]:
cbind(1:5,5:1,1:3)

Warning message in cbind(1:5, 5:1, 1:3):
"number of rows of result is not a multiple of vector length (arg 3)"


     [,1] [,2] [,3]
[1,] 1    5    1   
[2,] 2    4    2   
[3,] 3    3    3   
[4,] 4    2    1   
[5,] 5    1    2   

- 마찬가지로 경고메시지만 뜨고, 나머지는 순서에 따라 자동으로 채워준다.

`-` 예제2
: 열에 이름 설정하기

In [ ]:
cbind("col1"=1:6,"col2"=6:1,"col3"=1:3)

     col1 col2 col3
[1,] 1    6    1   
[2,] 2    5    2   
[3,] 3    4    3   
[4,] 4    3    1   
[5,] 5    2    2   
[6,] 6    1    3   

##### 방법4: dim 함수를 이용하는 방법

`-` 예제1

In [ ]:
A <- 1:10

In [ ]:
dim(A) <- c(2,5)

In [ ]:
A

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10  

In [ ]:
dim(A)

[1] 2 5

`-` 예제2: 예제1과 반대로 이미 만들어진 매트릭스를 벡터로 바꾸는 것도 가능하다.

`-` 방법1

In [ ]:
dim(A)

[1] 2 5

In [ ]:
dim(A) <- NULL

In [ ]:
dim(A)

NULL

In [ ]:
A

 [1]  1  2  3  4  5  6  7  8  9 10

`-` 방법2

In [ ]:
dim(A) <- c(2,5)
A

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10  

In [ ]:
dim(A) <- c()

In [ ]:
dim(A)

NULL

In [ ]:
A

 [1]  1  2  3  4  5  6  7  8  9 10

##### 방법5: array 함수를 이용하는 방법
: 기본적으로 $matrix()$와 유사 $ncol, nrow$ 대신 `dim=c()`을 사용

`-` 예시1

In [ ]:
array(1:12,dim=c(2,6))

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    3    5    7     9   11  
[2,] 2    4    6    8    10   12  

`-` 예시2

In [ ]:
array(1:12, dim=c(4,3))

     [,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12  

`-` 예시3

In [ ]:
array(1:2,dim=c(3,4))

     [,1] [,2] [,3] [,4]
[1,] 1    2    1    2   
[2,] 2    1    2    1   
[3,] 1    2    1    2   

`-` 예시4   
: 이건 메트릭스가 아님

In [ ]:
array(1:2,dim=c(3,4,2))

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    2    1    2
[2,]    2    1    2    1
[3,]    1    2    1    2

, , 2

     [,1] [,2] [,3] [,4]
[1,]    1    2    1    2
[2,]    2    1    2    1
[3,]    1    2    1    2


- $3×4$ 메트릭스가 stack되어서 쌓여져 있는 3차원 형태가 됨, 메트릭스 자체는 2차원 형태임

`-` 예시5   
: 이건 메트릭스가 아님

In [ ]:
array(1:2,dim=8)

[1] 1 2 1 2 1 2 1 2

- array를 사용하여 벡터를 만듦

`-` 기타

In [ ]:
as.matrix(c(1,2,3,4,5,6))

     [,1]
[1,] 1   
[2,] 2   
[3,] 3   
[4,] 4   
[5,] 5   
[6,] 6   

- 메트릭스로 변환

### 배열(array)

`-` 배열은 동일한 형의 원소를 p개의 차원으로 구성한 데이터 객체이다.

`-` 행렬은 2차원 배열의 일종이다. $p=2$

`-` 3차원 배열의 예시

In [ ]:
array(1:6,dim=c(3,2,2))

, , 1

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

, , 2

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6


`-` 추가학습 

아래와 같은 매트릭스를 만들고 A+B를 계산하라.

$A=\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8& 9 \end{bmatrix}$

$B=\begin{bmatrix} -1 & -2 & -3 \\ -4 & -5 & -6 \\ -7 & -8 & -10 \end{bmatrix}$

In [ ]:
A <- matrix(1:9,ncol=3,byrow = T)
A

     [,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9   

In [ ]:
B <- matrix(c(-1:-8,-10),ncol=3,byrow = T)
B

     [,1] [,2] [,3]
[1,] -1   -2    -3 
[2,] -4   -5    -6 
[3,] -7   -8   -10 

In [ ]:
A+B

     [,1] [,2] [,3]
[1,] 0    0     0  
[2,] 0    0     0  
[3,] 0    0    -1  