# IR 12.  매트릭스, 문법정리2(%>%, 벡터 및 행렬 결합, 매트릭스 원소 선택, 벡터 연산, 매트릭스 연산, 티블)

> "작성완료"

- toc:true
- branch: master
- badges: true
- comments: true
- [R]

---
# Introduce R 
- lecture: Introduce R_8-2nd week of lectures
- lecture date: 2021-10-29, 2021-11-02
- lecturer: Guebin choi
- study date: 2022-02-23, 2022-02-24
- author: Kione kim
---

In [ ]:
options(jupyter.rich_display=FALSE)

## 행렬과 연립방정식

`-` 예를들어 아래와 같은 문제가 있다고 하자. 

$\begin{cases}
w+2x+3y+4z=1 \\
2w+2x+y=9 \\
x-y=4 \\
3w+x-y+3y=7
\end{cases}$


이는 다음과 같이 표현할 수 있고

$\begin{bmatrix}
1 & 2 & 3 & 4 \\ 
2 & 2 & 1 & 0 \\
0 & 1 &-1 & 0 \\
3 & 1 &-1 & 3 
\end{bmatrix}
\begin{bmatrix}
w \\ x \\ y \\z 
\end{bmatrix}=\begin{bmatrix}
1 \\ 9 \\ 4 \\7 
\end{bmatrix}$


양변에 역행렬을 곱해주면 다음과 같이 된다.

$\begin{bmatrix}
w \\ x \\ y \\z 
\end{bmatrix}=\begin{bmatrix}
1 & 2 & 3 & 4 \\ 
2 & 2 & 1 & 0 \\
0 & 1 &-1 & 0 \\
3 & 1 &-1 & 3 
\end{bmatrix}^{-1}\begin{bmatrix}
1 \\ 9 \\ 4 \\7 
\end{bmatrix}$

### R로 구현

#### 역행렬: `solve()` -> $A^{-1}$

`-` 행렬의 곱셉: `%*%`

In [ ]:
A <- rbind(c(1,2,3,4),c(2,2,1,0),c(0,1,-1,0),c(3,1,-1,3))
A

     [,1] [,2] [,3] [,4]
[1,] 1    2     3   4   
[2,] 2    2     1   0   
[3,] 0    1    -1   0   
[4,] 3    1    -1   3   

In [ ]:
solve(A)

     [,1]       [,2]       [,3]       [,4]      
[1,] -0.1578947  0.2631579 -0.4210526  0.2105263
[2,]  0.1052632  0.1578947  0.6140351 -0.1403509
[3,]  0.1052632  0.1578947 -0.3859649 -0.1403509
[4,]  0.1578947 -0.2631579  0.0877193  0.1228070

In [ ]:
B <- cbind(c(1,9,4,7))
B

     [,1]
[1,] 1   
[2,] 9   
[3,] 4   
[4,] 7   

In [ ]:
solve(A) %*% B

     [,1]
[1,]  2  
[2,]  3  
[3,] -1  
[4,] -1  

- 답은 $(w,x,y,z) =$ $ (2,3,-1,-1)$ 이다.

`-` 아래와 같이해도 답은 동일하게 나옴.

In [ ]:
B <- c(1,9,4,7)
B

[1] 1 9 4 7

In [ ]:
solve(A) %*% B

     [,1]
[1,]  2  
[2,]  3  
[3,] -1  
[4,] -1  

## 문법정리 2

### %>%

`-` tidyverse 중 하나인 dplyr 기능

`-` 함수의 첫번째 입력이 `%>% 연산자`의 왼쪽의 결과로 생각한다.

`-` 하나의 입력만 받는 함수라면 함수이름만 쓸 수 있다.

`-` 첫 입력을 생략한다는 것이 포인트

In [ ]:
library(tidyverse)

`-` 예시1

In [ ]:
f <- function(x) x+3

In [ ]:
f(3)

[1] 6

In [ ]:
3 %>% f

[1] 6

`-` 예시2

In [ ]:
f <- function(x,y) x**2+y

In [ ]:
f(3,2)

[1] 11

In [ ]:
3 %>% f(2)

[1] 11

### 두 개 이상의 벡터, 행렬을 결합

### 벡터의 결합

In [ ]:
x <- c(1,2,3)
y <- c(4,5,6,7)

In [ ]:
x
y

[1] 1 2 3

[1] 4 5 6 7

In [ ]:
c(x,y)

[1] 1 2 3 4 5 6 7

In [ ]:
c(y,x)

[1] 4 5 6 7 1 2 3

In [ ]:
c(x,8,8,8,y)

 [1] 1 2 3 8 8 8 4 5 6 7

- $c()$에서 $c$는 결합하라라는 의미

`-` 예제2

In [ ]:
x<-c(1,2,3)
y<-c(4,5,6)

In [ ]:
cbind(x,y)

     x y
[1,] 1 4
[2,] 2 5
[3,] 3 6

`-` 예제2-1

In [ ]:
x<-c(1,2,3,4)
y<-c(1,2)

In [ ]:
cbind(x,y)

     x y
[1,] 1 1
[2,] 2 2
[3,] 3 1
[4,] 4 2

`-` 예제2-2

In [ ]:
x<-c(1,2,3,4)
cbind(1,x)

       x
[1,] 1 1
[2,] 1 2
[3,] 1 3
[4,] 1 4

`-` 예제3

In [ ]:
x<-c(1,2,3,4)
y<-c(1,2)
rbind(x,y)

  [,1] [,2] [,3] [,4]
x 1    2    3    4   
y 1    2    1    2   

`-` 예제4

In [ ]:
x<-c(1,2,3)
y<-c(4,5)
cbind(1,c(x,y))

     [,1] [,2]
[1,] 1    1   
[2,] 1    2   
[3,] 1    3   
[4,] 1    4   
[5,] 1    5   

### 행렬의 결합

`-` 예제1

In [ ]:
x<-rbind(1:5,6:10)
y<-c(1,2)

In [ ]:
x

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10  

In [ ]:
y

[1] 1 2

In [ ]:
cbind(x,y)

                y
[1,] 1 2 3 4  5 1
[2,] 6 7 8 9 10 2

In [ ]:
cbind(x,y,y)

                y y
[1,] 1 2 3 4  5 1 1
[2,] 6 7 8 9 10 2 2

`-` 열의 이름은 다음과 같이 지울 수 있다.

In [ ]:
xyy = cbind(x,y,y)
colnames(xyy)

[1] ""  ""  ""  ""  ""  "y" "y"

In [ ]:
colnames(x)

NULL

In [ ]:
colnames(xyy) = NULL

In [ ]:
xyy

     [,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 1    2    3    4     5   1    1   
[2,] 6    7    8    9    10   2    2   

`-` 예제2

In [ ]:
x <- rbind(1:5,6:10)
rbind(x,1)

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10  
[3,] 1    1    1    1     1  

`-` 예제3

In [ ]:
x <- rbind(1:5,6:10,1:5)
y <- cbind(1:3,4:6,7:9)

In [ ]:
x

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10  
[3,] 1    2    3    4     5  

In [ ]:
y

     [,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9   

In [ ]:
cbind(x,y)

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1    2    3    4     5   1    4    7   
[2,] 6    7    8    9    10   2    5    8   
[3,] 1    2    3    4     5   3    6    9   

In [ ]:
rbind(x,y)

ERROR: Error in rbind(x, y): 각각의 행렬이 가진 열의 개수는 반드시 서로 일치해야 합니다 (인자 2를 참고하세요)


- 차원이 맞지 않아 오류

### 매트릭스 원소 선택

In [ ]:
x <- rbind(1:5,6:10,1:5)
x

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10  
[3,] 1    2    3    4     5  

`-` 예제1

In [ ]:
x[,1]

[1] 1 6 1

- 선택된 원소는 자동으로 벡터화 된다.

In [ ]:
X=x[,1]
X

[1] 1 6 1

In [ ]:
dim(X)

NULL

- 벡터화되어서 행렬의 차원이 존재하지 않는다.

In [ ]:
dim(X) <- c(3,1)
X

     [,1]
[1,] 1   
[2,] 6   
[3,] 1   

`-` 예제2

In [ ]:
x[,1:2]

     [,1] [,2]
[1,] 1    2   
[2,] 6    7   
[3,] 1    2   

`-` 예제3

In [ ]:
x[,-1]

     [,1] [,2] [,3] [,4]
[1,] 2    3    4     5  
[2,] 7    8    9    10  
[3,] 2    3    4     5  

`-` 예제4

In [ ]:
x[,-(1:2)]

     [,1] [,2] [,3]
[1,] 3    4     5  
[2,] 8    9    10  
[3,] 3    4     5  

`-` 예제5

In [ ]:
x[1:2,]

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10  

`-` 예제6

In [ ]:
x[1:2,3:4]

     [,1] [,2]
[1,] 3    4   
[2,] 8    9   

`-` 예제7

In [ ]:
x[1:2,-1]

     [,1] [,2] [,3] [,4]
[1,] 2    3    4     5  
[2,] 7    8    9    10  

### 벡터관련연산

`-` 예제1

In [ ]:
c(1,2,3) %in% c(1,2,4)

[1]  TRUE  TRUE FALSE

`-` 예제2 : 합집합

In [ ]:
union(c(1,2,2),c(1,3,5)) # 합집합

[1] 1 2 3 5

`-` 예제3 : 교집합

In [ ]:
intersect(1:4,3:6)

[1] 3 4

`-` 예제4 : 내적계산 (`%*%`)

In [ ]:
x=1:5

In [ ]:
x %*% x

     [,1]
[1,] 55  

`-` 예제5 : 외적계산(`%o%`)

In [ ]:
x=1:5

In [ ]:
x %o% x

     [,1] [,2] [,3] [,4] [,5]
[1,] 1     2    3    4    5  
[2,] 2     4    6    8   10  
[3,] 3     6    9   12   15  
[4,] 4     8   12   16   20  
[5,] 5    10   15   20   25  

### 매트릭스 관련 연산

`-` 예제1 : 전치행렬

In [ ]:
A <- cbind(c(1,2,3),c(4,5,6),c(7,8,9))
A

     [,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9   

In [ ]:
t(A)

     [,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9   

`-` 예제2 : 상수 곱하기

In [ ]:
A = cbind(c(1,2,3),c(4,5,6),c(7,8,9))
A

     [,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9   

In [ ]:
-A

     [,1] [,2] [,3]
[1,] -1   -4   -7  
[2,] -2   -5   -8  
[3,] -3   -6   -9  

In [ ]:
A*2

     [,1] [,2] [,3]
[1,] 2     8   14  
[2,] 4    10   16  
[3,] 6    12   18  

In [ ]:
A**2

     [,1] [,2] [,3]
[1,] 1    16   49  
[2,] 4    25   64  
[3,] 9    36   81  

`-` 예제3 : 덧셈, 뺄셈

In [ ]:
A=cbind(c(1,2,3),c(4,5,6),c(7,8,9))
B=cbind(1:3,2:4,3:5)

In [ ]:
A

     [,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9   

In [ ]:
B

     [,1] [,2] [,3]
[1,] 1    2    3   
[2,] 2    3    4   
[3,] 3    4    5   

In [ ]:
A+B

     [,1] [,2] [,3]
[1,] 2     6   10  
[2,] 4     8   12  
[3,] 6    10   14  

`-` 예제4 : 곱셈

In [ ]:
A=cbind(c(1,2),c(3,4))
A

     [,1] [,2]
[1,] 1    3   
[2,] 2    4   

In [ ]:
A %*% A

     [,1] [,2]
[1,]  7   15  
[2,] 10   22  

`-` 예제5 : 역행렬

In [ ]:
A=rbind(c(1,3),c(3,1))
A

     [,1] [,2]
[1,] 1    3   
[2,] 3    1   

In [ ]:
solve(A)

     [,1]   [,2]  
[1,] -0.125  0.375
[2,]  0.375 -0.125

In [ ]:
A %*% solve(A)

     [,1] [,2]
[1,] 1    0   
[2,] 0    1   

### 티블 만드는 방법

`-` 벡터로 만들기

In [ ]:
x<-c(1,2,3)
y<-c('a','b','c')

In [ ]:
tb=tibble(x=x,y=y)

In [ ]:
tb

  x y
1 1 a
2 2 b
3 3 c

In [ ]:
tb$x

[1] 1 2 3

In [ ]:
tb$y

[1] "a" "b" "c"

- column간의 원소형태가 달라도 됨(x는 numeric, y는 character)

`-` 메트릭스로 만들기

In [ ]:
X=cbind(1:5,16:20)
X

     [,1] [,2]
[1,] 1    16  
[2,] 2    17  
[3,] 3    18  
[4,] 4    19  
[5,] 5    20  

In [ ]:
tb=as_tibble(X)
tb

  V1 V2
1 1  16
2 2  17
3 3  18
4 4  19
5 5  20

In [ ]:
tb$V1

[1] 1 2 3 4 5

In [ ]:
tb$V2

[1] 16 17 18 19 20

#### 티블을 사용하는 이유:

`1. mutate`

`2. filter`

`1.mutate`

In [ ]:
tb %>% mutate(V3=3*V1+V2,V4=V3/V1,V5=V4-V3)

  V1 V2 V3 V4    V5    
1 1  16 19 19.00   0.00
2 2  17 23 11.50 -11.50
3 3  18 27  9.00 -18.00
4 4  19 31  7.75 -23.25
5 5  20 35  7.00 -28.00

In [ ]:
mutate(tb,V3=3*V1+V2,V4=V3/V1,V5=V4-V3)

  V1 V2 V3 V4    V5    
1 1  16 19 19.00   0.00
2 2  17 23 11.50 -11.50
3 3  18 27  9.00 -18.00
4 4  19 31  7.75 -23.25
5 5  20 35  7.00 -28.00

- 새로운 열을 만드는데 편리함

In [ ]:
tb

  V1 V2
1 1  16
2 2  17
3 3  18
4 4  19
5 5  20

- 기존의 tb는 변하지 않음

`2.filter`

In [ ]:
tb_ <- tb %>% mutate(V3=3*V1+V2,V4=V3/V1,V5=V4-V3)
tb_

  V1 V2 V3 V4    V5    
1 1  16 19 19.00   0.00
2 2  17 23 11.50 -11.50
3 3  18 27  9.00 -18.00
4 4  19 31  7.75 -23.25
5 5  20 35  7.00 -28.00

In [ ]:
tb_ %>% filter(V1>3,V4<10)

  V1 V2 V3 V4   V5    
1 4  19 31 7.75 -23.25
2 5  20 35 7.00 -28.00

#### mutate + filter

In [ ]:
tb

  V1 V2
1 1  16
2 2  17
3 3  18
4 4  19
5 5  20

In [ ]:
tb %>% mutate(V3=(V2-mean(V2))/sum(V1))

  V1 V2 V3         
1 1  16 -0.13333333
2 2  17 -0.06666667
3 3  18  0.00000000
4 4  19  0.06666667
5 5  20  0.13333333

In [ ]:
tb %>% mutate(V3=(V2-mean(V2))/sum(V1)) %>% filter(V3>0)

  V1 V2 V3        
1 4  19 0.06666667
2 5  20 0.13333333

- mutate와 filter를 함께 사용할 수 있다.