# IR 8. 숫자 카드 게임(2019 국가 교육기관 코딩테스트)
> "작성완료"

- toc:true
- branch: master
- badges: true
- comments: true
- [R]

---
# Introduce R 
- lecture: Introduce R_6nd week of lectures
- lecture date: 2021-10-19
- lecturer: Guebin choi
- study date: 2022-02-15
- author: Kione kim
---

In [212]:
#hide
options(jupyter.plot_scale=3)
options(jupyter.display_mimetypes=c("text/html"))
options(jupyter.rich_display=FALSE)
options(repr.plot.width=6,repr.plot.height=6,repr.plot.res=300)
options(max.print=1000)

In [67]:
library(tidyverse)

## 숫자 카드 게임 (2019 국가 교육기관 코딩테스트) 

숫자 카드 게임은 여러개의 숫자중에서 가장 높은 숫자가 쓰인 카드를 한 장 뽑는 게임이다.

단, 게임의 룰을 지키며 뽑아야 하고 룰은 다음과 같다.
- 숫자가 쓰인 카드들이 N × M 형태로 놓여있다.
- 먼저 뽑고자 하는 카드가 포함되어 있는 행을 선택한다.
- 그 다음 선택된 행에 포함된 카드들 중에서 가장 숫자가 낮은 카드를 뽑아야 한다. 
- 따라서 처음에 카드를 골라낼 행을 선택할 때, 이후에 해당 행에서 가장 숫자가 낮은 카드를 뽑을 것을 고려하여 최종적으로 가장 높은 숫자의 카드를 뽑을 수 있도록 전략을 세워야 한다.

`-` 예시1
```
입력
3 1 2
4 1 4
2 2 2

출력
2
```

`-` 예시2
```
입력
7 3 1 8
3 3 3 4

출력
3
```

``` R
- 풀이법:
1. 함수의 입력에 넣을 수 있도록 행렬의 형태로 만든다.
2. 각 행의 최솟값들을 뽑아 벡터를 만들고 그 벡터 값 중 최댓값을 뽑는다.


- 구체적인 전략: 
1. A의 각 행(row)을 돌아가면서 가장 작은 숫자를 찾아 기록한다.
2. 기록한 숫자들을 모아서 벡터로 만든다.
3. 벡터의 최댓값을 구한다.

- 수행에 필요한 skill:
A의 첫 번째 행, 두번째 행, 세번째 행의 최솟값을 순서대로 뽑을 수 있어야 한다.
```

`1.` 행렬의 형태

In [16]:
a1 <- c(3,1,2)
a2 <- c(4,1,4)
a3 <- c(2,2,2)

In [17]:
a = rbind(a1,a2,a3)
a

   [,1] [,2] [,3]
a1 3    1    2   
a2 4    1    4   
a3 2    2    2   

- 아래와 같이 해도 된다.

In [33]:
a = rbind(c(3,1,2), c(4,1,4), c(2,2,2))
a

     [,1] [,2] [,3]
[1,] 3    1    2   
[2,] 4    1    4   
[3,] 2    2    2   

In [45]:
a

     [,1] [,2] [,3]
[1,] 3    1    2   
[2,] 4    1    4   
[3,] 2    2    2   

`2.` 벡터 출력

In [46]:
(a[1,]) # a[i,] -> a의 i번째 행을 뽑을 수 있다. 

[1] 3 1 2

In [47]:
min(a[1,]) # min(a[i,]) -> a의 i번째 행의 최솟값을 출력해준다.

[1] 1

In [51]:
for (i in 1:3) print((min(a[i,])))

[1] 1
[1] 1
[1] 2


In [52]:
vec <- c()
for (i in 1:3) vec[i] <- (min(a[i,]))
vec

[1] 1 1 2

In [53]:
max(vec)

[1] 2

``` R
vec <- c()
for (i in 1:3) vec[i] <- (min(a[i,]))
처럼 코드를 작성하면, 
for (i in 1:3) print((min(a[i,]))) 에서 출력으로 나오는 값을 벡터로 저장할 수 있다.
```

`-` 예시 2에 대한 적용

In [58]:
a <- rbind(c(7,3,1,8), c(3,3,3,4))
a

     [,1] [,2] [,3] [,4]
[1,] 7    3    1    8   
[2,] 3    3    3    4   

In [59]:
vec <- c()
for (i in 1:2) vec[i] <- (min(a[i,]))
vec

[1] 1 3

In [60]:
max(vec)

[1] 3

`추가 학습`: 
``` 
입력
3 4 5 1
7 7 7 2
8 1 8 2
3 3 4 5

출력은 ? 
```

In [63]:
a <- rbind(c(3,4,5,1),c(7,7,7,2),c(8,1,8,2),c(3,3,4,5))
a

     [,1] [,2] [,3] [,4]
[1,] 3    4    5    1   
[2,] 7    7    7    2   
[3,] 8    1    8    2   
[4,] 3    3    4    5   

In [64]:
vec <- c()
for (i in 1:4) vec[i] <- min(a[i,])
vec

[1] 1 2 1 3

In [65]:
max(vec)

[1] 3