# IR 10. 볼링공문제(2019 SW마에스트로 입학 테스트), 벡터만 사용한 풀이, 매트릭스를 이용한 풀이, 데이터프레임을 활용한 풀이
> "작성완료"

- toc:true
- branch: master
- badges: true
- comments: true
- [R]

---
# Introduce R 
- lecture: Introduce R_7-2nd week of lectures
- lecture date: 2021-10-26
- lecturer: Guebin choi
- study date: 2022-02-21
- author: Kione kim
---

In [ ]:
#hide
options(jupyter.plot_scale=3)
options(jupyter.display_mimetypes=c("text/html"))
options(jupyter.rich_display=FALSE)
options(repr.plot.width=6,repr.plot.height=6,repr.plot.res=300)
options(max.print=1000)

## 볼링공문제 (2019 SW마에스트로 입학 테스트)

A,B 두 사람이 볼링을 치고 있습니다. 두 사람은 서로 무게가 다른 볼링공을 고르려고 합니다. 볼링공은 총 N개가 있으며 각 볼링공마다 무게가 적혀 있고, 공의 번호는 1번부터 순서대로 부여됩니다. 또한 같은 무게의 공이 여러개 있을 수 있지만, 서로 다른 공으로 간주합니다. 볼링공의 무게는 1부터 M까지의 자연수 형태로 존재합니다. 

예를들어 N이 5이고, M이 3이며 각각의 무게가 차례대로 1,3,2,3,2일 때 각 공의 번호가 차례대로 1번부터 5번까지 부여됩니다. 이때 두 사람이 고를 수 있는 볼링공 번호의 조합을 구하면 다음과 같습니다. 

(1번,2번), (1번,3번), (1번,4번), (1번,5번), (2번,3번), (2번,5번), (3번,4번), (4번,5번)

결과적으로 두 사람이 공을 고르는 경우의 수는 8가지입니다. N개의 공의 무게가 각각 주어질 때, 두 사람이 볼링공을 고르는 경우의 수를 구하는 프로그램을 작성하세요. 

`-` $N$개의 볼링공의 무게를 각각 $x_1,\dots,x_N$ 이라고 하자.  $x_1,\dots, x_N$은 $\{1,\dots, M\}$사이의 자연수의 값을 갖고 서로 같은 값을 가질 수 있다

``` R
입력:
N: 5 M: 3
xi: 1 3 2 3 2
출력:
8
```

- $(a_1,\dots, a_5)=(1,3,2,3,2)$일 때   
$(a_1,a_2), (a_1,a_3), (a_1,a_4), (a_1,a_5), (a_2,a_3), (a_2,a_5), (a_3,a_4), (a_4,a_5)$

### 풀이1 ~ 풀이2: 벡터만 사용한 풀이(매트릭스 사용 x)

#### 풀이1

`-` 잘못된 풀이

In [ ]:
a <- c(1,3,2,3,2)
a

[1] 1 3 2 3 2

In [ ]:
count = 0
for (i in 1:5){
    for (j in 1:5){
        if (a[i] != a[j]) count <- count +1
    }
}

In [ ]:
count

[1] 16

- 답은 8인데 8의 두 배인 16이 계산됨

- 생각해보니, 위의 코드는 무게가 각각 1과 2인 $(x1,x3)$과 $(x3,x1)$을 중복하여 계산했을 것임   
즉, $(a_1,a_2), (a_1,a_3), (a_1,a_4), (a_1,a_5), (a_2,a_3), (a_2,a_5), (a_3,a_4), (a_4,a_5)$에    
순서가 바뀐 $(a_2,a_1), (a_3,a_1), (a_4,a_1), (a_5,a_1), (a_3,a_2), (a_5,a_2), (a_4,a_3), (a_5,a_4)$이 중복되어 계산되었음

- 이를 해결하기 위해 $(a_2,a_1), (a_3,a_1), (a_4,a_1), (a_5,a_1), (a_3,a_2), (a_5,a_2), (a_4,a_3), (a_5,a_4)$을 제외시켜주면 되는데,   
$(a_1,a_2), (a_1,a_3), (a_1,a_4), (a_1,a_5), (a_2,a_3), (a_2,a_5), (a_3,a_4), (a_4,a_5)$을 살펴보니 $a[i]$가 $a[j]$보다 작은 것을 알 수 있다.   
이는 우리가 경우의 수를 계산할 때 작은 수부터 오름차순으로 계산해나가기 때문이다.    
따라서 $a[i] < a[j]$인 조건을 주면 된다.

##### 수정된 풀이(풀이 1)

In [ ]:
count = 0
for (i in 1:5){
    for (j in 1:5){
        if (a[i] != a[j] & a[i] < a[j]) count <- count +1
    }
}

In [ ]:
count

[1] 8

#### 풀이2

In [ ]:
count = 0
for (i in 1:5){
    for (j in i:5){
        if (a[i] != a[j]) count <- count+1
    }
}

In [ ]:
count

[1] 8

``` R
위 코드 풀이:
i = 1 일 때
j = 1,2,3,4,5
에 대한 if문 실행
i = 2 일 때
j = 2,3,4,5
if문
i = 3 일 때
j = 3,4,5
if문
i = 4 일 때
j = 4,5
if문
i = 5 일 때
j = 5
if문

: 조건을 j에 대한 for문에 적용시켰고 보다 간결해짐
```

### 풀이3 ~ 풀이5: 매트릭스를 사용한 풀이

#### 풀이 3

In [ ]:
rep(0,25*2) # 0을 25*2개 리턴

 [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[39] 0 0 0 0 0 0 0 0 0 0 0 0

In [ ]:
a <- c(1,3,2,3,2)
A = rep(0,25*2)
dim(A) <- c(25,2)
A

      [,1] [,2]
 [1,] 0    0   
 [2,] 0    0   
 [3,] 0    0   
 [4,] 0    0   
 [5,] 0    0   
 [6,] 0    0   
 [7,] 0    0   
 [8,] 0    0   
 [9,] 0    0   
[10,] 0    0   
[11,] 0    0   
[12,] 0    0   
[13,] 0    0   
[14,] 0    0   
[15,] 0    0   
[16,] 0    0   
[17,] 0    0   
[18,] 0    0   
[19,] 0    0   
[20,] 0    0   
[21,] 0    0   
[22,] 0    0   
[23,] 0    0   
[24,] 0    0   
[25,] 0    0   

- 25 × 2 행렬을 만듦

In [ ]:
k=1
for (i in 1:5){
    for (j in 1:5){
        A[k,] <- c(a[i],a[j])
        k=k+1
    }
}

In [ ]:
A

      [,1] [,2]
 [1,] 1    1   
 [2,] 1    3   
 [3,] 1    2   
 [4,] 1    3   
 [5,] 1    2   
 [6,] 3    1   
 [7,] 3    3   
 [8,] 3    2   
 [9,] 3    3   
[10,] 3    2   
[11,] 2    1   
[12,] 2    3   
[13,] 2    2   
[14,] 2    3   
[15,] 2    2   
[16,] 3    1   
[17,] 3    3   
[18,] 3    2   
[19,] 3    3   
[20,] 3    2   
[21,] 2    1   
[22,] 2    3   
[23,] 2    2   
[24,] 2    3   
[25,] 2    2   

In [ ]:
A[1,]
A[2,]
A[5,]
A[20,]
k=23
A[k,]

[1] 1 1

[1] 1 3

[1] 1 2

[1] 3 2

[1] 2 2

``` R
k=1
for (i in 1:5){
    for (j in 1:5){
        A[k,] <- c(a[i],a[j])
        k=k+1
    }
}

코드 풀이: 
1. A[k,]: k값에 해당하는 행을 출력
2. A[k,] <- c(3,2): k값에 해당하는 행에 c(3,2)를 입력
3. i가 1일 때 j는 1,2,3,4,5의 값을 a[i],a[j]에 입력하여 백터화하여 A[k,]에 입력
i가 2일 때 j는 1,2,3,4,5의 값을 a[i],a[j]에 입력하여 백터화하여 A[k,]에 입력위와 동일하게 입력
i가 3,4,5일 때도 동일
4. k=k+1:(처음에 k=1으로 입력했기 때문에 A[k,]는 첫번째 행이고) 반복을 한 번 실행할 때마다 k값이 1씩 커짐 
-> A[1,], A[2,], A[3,], ... , A[25,]로 모든 행에 위 3.의 입력을 실행
```

In [ ]:
A

      [,1] [,2]
 [1,] 1    1   
 [2,] 1    3   
 [3,] 1    2   
 [4,] 1    3   
 [5,] 1    2   
 [6,] 3    1   
 [7,] 3    3   
 [8,] 3    2   
 [9,] 3    3   
[10,] 3    2   
[11,] 2    1   
[12,] 2    3   
[13,] 2    2   
[14,] 2    3   
[15,] 2    2   
[16,] 3    1   
[17,] 3    3   
[18,] 3    2   
[19,] 3    3   
[20,] 3    2   
[21,] 2    1   
[22,] 2    3   
[23,] 2    2   
[24,] 2    3   
[25,] 2    2   

- 여기까지 하면 조건을 걸어두지 않은 상태   

`-` $1)$ 같은 무게를 뽑지 않고    $2)$ 중복되는 경우 제외   
위 두 조건을 설정해야 함

In [ ]:
vec1 <- c()
for (i in 1:25){
    vec1[i] <- A[i,1] != A[i,2]
}

In [ ]:
vec1

 [1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE
[13] FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE FALSE  TRUE
[25] FALSE

`-` 1

In [ ]:
vec2 <- c()
k=1
for (i in 1:5){
    for (j in 1:5){
        vec2[k] <- (i<j)
        k=k+1
    }
}

In [ ]:
vec2

 [1] FALSE  TRUE  TRUE  TRUE  TRUE FALSE FALSE  TRUE  TRUE  TRUE FALSE FALSE
[13] FALSE  TRUE  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE
[25] FALSE

In [ ]:
sum(vec1 & vec2)

[1] 8

`-` 2

In [ ]:
vec2 <- c()
for (i in 1:25){
    vec2[i] <- A[i,1] < A[i,2]
}

In [ ]:
vec2

 [1] FALSE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE
[13] FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE
[25] FALSE

In [ ]:
sum(vec1 & vec2)

[1] 8

`-` 위 코드를 간결하게 정리하면 아래와 같음

In [ ]:
vec1 <- c()
vec2 <- c()
for (k in 1:25){
    vec1[k] <- A[k,1] != A[k,2]     # vec1가 아닌 vec1[k]를 입력
    vec2[k] <- A[k,1] < A[k,2]      # 마찬가지로 vec2가 아닌 vec2[k]를 입력
}

In [ ]:
vec1

 [1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE
[13] FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE FALSE  TRUE
[25] FALSE

In [ ]:
vec2

 [1] FALSE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE
[13] FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE
[25] FALSE

In [ ]:
sum(vec1 & vec2)

[1] 8

#### 풀이4

: 굳이 vec1, vec2를 for문 을 통해 구할 필요가 없음

In [ ]:
a = c(1,3,2,3,2)
A = rep(0,25*2)
dim(A) <- c(25,2)
k=1
for (i in 1:5){
    for (j in 1:5){
        A[k,] <- c(a[i],a[j])
        k=k+1
    }
}
A

      [,1] [,2]
 [1,] 1    1   
 [2,] 1    3   
 [3,] 1    2   
 [4,] 1    3   
 [5,] 1    2   
 [6,] 3    1   
 [7,] 3    3   
 [8,] 3    2   
 [9,] 3    3   
[10,] 3    2   
[11,] 2    1   
[12,] 2    3   
[13,] 2    2   
[14,] 2    3   
[15,] 2    2   
[16,] 3    1   
[17,] 3    3   
[18,] 3    2   
[19,] 3    3   
[20,] 3    2   
[21,] 2    1   
[22,] 2    3   
[23,] 2    2   
[24,] 2    3   
[25,] 2    2   

In [ ]:
vec1 <- A[,1] != A[,2]
vec1

 [1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE
[13] FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE FALSE  TRUE
[25] FALSE

In [ ]:
vec2 <- A[,1] < A[,2]
vec2

 [1] FALSE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE
[13] FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE
[25] FALSE

In [ ]:
sum(vec1 & vec2)

[1] 8

#### 풀이5

: 생각해보니, $2)$ 중복되는 경우 제외 이 성립하면 $1)$ 같은 무게를 뽑지 않고 또한 성립하게 된다. 왜냐하면, $A[,1] < A[,2]$에는 $A[,1] ≠ A[,2]$이 포함되어 있기 때문(작으면 같을 수 없기 때문)

In [ ]:
a <- c(1,3,2,3,2)
A <- rep(0,25*2)
dim(A) <- c(25,2)
k=1
for (i in 1:5){
    for (j in 1:5){
        A[k,] <- c(a[i],a[j])
        k=k+1
    }
}
A

      [,1] [,2]
 [1,] 1    1   
 [2,] 1    3   
 [3,] 1    2   
 [4,] 1    3   
 [5,] 1    2   
 [6,] 3    1   
 [7,] 3    3   
 [8,] 3    2   
 [9,] 3    3   
[10,] 3    2   
[11,] 2    1   
[12,] 2    3   
[13,] 2    2   
[14,] 2    3   
[15,] 2    2   
[16,] 3    1   
[17,] 3    3   
[18,] 3    2   
[19,] 3    3   
[20,] 3    2   
[21,] 2    1   
[22,] 2    3   
[23,] 2    2   
[24,] 2    3   
[25,] 2    2   

In [ ]:
vec2 <- A[,1] < A[,2]

In [ ]:
vec2

 [1] FALSE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE
[13] FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE
[25] FALSE

In [ ]:
sum(vec2)

[1] 8

In [ ]:
sum(A[,1] < A[,2])

[1] 8

**`-` 풀이2가 가장 간결하고 루프도 적게 돌아가지만 틀리기 쉬운 코드이다. 즉 디버깅(오류수정)이 어려워 예외사항을 처리하기 힘들 수 있다.(코딩테스트에서는 예외사항을 잘 처리해야 하는 문제가 자주 출제되곤 하니 디버깅에 용이한 풀이법으로 익히는 것이 좋다.)**

### 풀이6 ~ 풀이8

`풀이6:` 데이터프레임 활용 $\to$ 사용하기 쉽고 확장성이 좋음   
`풀이7,8:` 코드가 간결하나, 에러가 발생할 수 있음

#### 풀이6

: A를 구해주는 함수인 `expand.grid()`이용(R에 내장)

`expand.grid():` 벡터를 입력으로 받아 그 벡터의 원소가 만들어내는 순서쌍 조합을 데이터프레임 형태로 반환하는 기능을 하는 함수   
`mutate():` 데이터프레임에서만 쓸수 있는 함수로 새로운 열을 만들어내는 기능을 한다. 특히, 기존에 있는 컬럼을 활용한 파생되는 컬럼을 만들 수 있는 장점이 있다.   
`filter():` 데이터프레임에서 특정조건을 만족하는 행을 필터링하는 기능을 한다.   
`count():` 데이터프레임에서 행의 숫자를 세어주는 기능을 한다. 이는 데이터프레임 형태로 반환하는 불편함이 있다.(숫자가 하나이기 때문)   
`as.numeric():` 숫자로 변환해주는 기능을 한다.

In [ ]:
# library(tidyverse)

In [ ]:
a <- c(1,3,2,3,2)
a

[1] 1 3 2 3 2

In [ ]:
A = expand.grid(a,a)
A

   Var1 Var2
1  1    1   
2  3    1   
3  2    1   
4  3    1   
5  2    1   
6  1    3   
7  3    3   
8  2    3   
9  3    3   
10 2    3   
11 1    2   
12 3    2   
13 2    2   
14 3    2   
15 2    2   
16 1    3   
17 3    3   
18 2    3   
19 3    3   
20 2    3   
21 1    2   
22 3    2   
23 2    2   
24 3    2   
25 2    2   

- A는 풀이 3~5에서 다루었던 메트릭스 형태가 아니고 dataframe 형태임

In [ ]:
A %>% mutate(C= Var1 > Var2) # 조건2

   Var1 Var2 C    
1  1    1    FALSE
2  3    1     TRUE
3  2    1     TRUE
4  3    1     TRUE
5  2    1     TRUE
6  1    3    FALSE
7  3    3    FALSE
8  2    3    FALSE
9  3    3    FALSE
10 2    3    FALSE
11 1    2    FALSE
12 3    2     TRUE
13 2    2    FALSE
14 3    2     TRUE
15 2    2    FALSE
16 1    3    FALSE
17 3    3    FALSE
18 2    3    FALSE
19 3    3    FALSE
20 2    3    FALSE
21 1    2    FALSE
22 3    2     TRUE
23 2    2    FALSE
24 3    2     TRUE
25 2    2    FALSE

In [ ]:
A %>% mutate(C= Var1 > Var2) %>% filter(C==TRUE) # 조건2를 만족하는 경우

  Var1 Var2 C   
1 3    1    TRUE
2 2    1    TRUE
3 3    1    TRUE
4 2    1    TRUE
5 3    2    TRUE
6 3    2    TRUE
7 3    2    TRUE
8 3    2    TRUE

In [ ]:
A %>% mutate(C= Var1 > Var2) %>% filter(C==TRUE) %>% count

  n
1 8

In [ ]:
A %>% mutate(C= Var1 > Var2) %>% filter(C==TRUE) %>% count %>% as.numeric

[1] 8

---

`-` 열을 추출하는 방법

In [ ]:
A[,1]

 [1] 1 3 2 3 2 1 3 2 3 2 1 3 2 3 2 1 3 2 3 2 1 3 2 3 2

In [ ]:
A['Var1']

   Var1
1  1   
2  3   
3  2   
4  3   
5  2   
6  1   
7  3   
8  2   
9  3   
10 2   
11 1   
12 3   
13 2   
14 3   
15 2   
16 1   
17 3   
18 2   
19 3   
20 2   
21 1   
22 3   
23 2   
24 3   
25 2   

In [ ]:
A $ Var1

 [1] 1 3 2 3 2 1 3 2 3 2 1 3 2 3 2 1 3 2 3 2 1 3 2 3 2

---

#### 풀이7

`%*% 연산자:` 메트릭스 간의 곱셈을 하는 기능   
`upper.tri():` 행렬의 상단부에 위치한 원소들은 TRUE, 대각선과 하단부에 위치한 원소들은 FALSE를 취해주는 기능   
`%in%:` 원소가 포함되어 있는지 확인하는 기능으로 포함되어 있으면 TRUE, 포함되어 있지 않으면 FALSE를 반환

`%in% 예시(★★★)`

In [ ]:
a_ <- c(6,6,7,9,1,2,3,8,5,5,5)

In [ ]:
a_ %in% c(5,6)

 [1]  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE

In [ ]:
a <- c(1,3,2,3,2)
a

[1] 1 3 2 3 2

---

In [ ]:
a1 <- a
a2 <- a

In [ ]:
dim(a1) <- c(5,1)
dim(a2) <- c(1,5)

In [ ]:
a1 # 5×1 matrix

     [,1]
[1,] 1   
[2,] 3   
[3,] 2   
[4,] 3   
[5,] 2   

In [ ]:
a2 # 1×5 matrix

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    3    2    3    2   

In [ ]:
a1 %*% a2 # 5×5 matrix

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    3    2    3    2   
[2,] 3    9    6    9    6   
[3,] 2    6    4    6    4   
[4,] 3    9    6    9    6   
[5,] 2    6    4    6    4   

In [ ]:
A = a1 %*% a2
A

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    3    2    3    2   
[2,] 3    9    6    9    6   
[3,] 2    6    4    6    4   
[4,] 3    9    6    9    6   
[5,] 2    6    4    6    4   

In [ ]:
upper.tri(A)

     [,1]  [,2]  [,3]  [,4]  [,5] 
[1,] FALSE  TRUE  TRUE  TRUE  TRUE
[2,] FALSE FALSE  TRUE  TRUE  TRUE
[3,] FALSE FALSE FALSE  TRUE  TRUE
[4,] FALSE FALSE FALSE FALSE  TRUE
[5,] FALSE FALSE FALSE FALSE FALSE

In [ ]:
A[upper.tri(A)]

 [1] 3 2 6 3 9 6 2 6 4 6

In [ ]:
sum(!A[upper.tri(A)] %in% c(4,9)) # 벡터 원소 중 4와 9의 값을 갖지 않는 원소의 계수

[1] 8

#### 풀이8

: A를 바로 구해주는 함수인 `outer()`이용(R에 내장)

In [ ]:
A

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    3    2    3    2   
[2,] 3    9    6    9    6   
[3,] 2    6    4    6    4   
[4,] 3    9    6    9    6   
[5,] 2    6    4    6    4   

In [ ]:
a <- c(1,3,2,3,2)
a

[1] 1 3 2 3 2

In [ ]:
A = outer(a,a)
A

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    3    2    3    2   
[2,] 3    9    6    9    6   
[3,] 2    6    4    6    4   
[4,] 3    9    6    9    6   
[5,] 2    6    4    6    4   

In [ ]:
sum(!A[upper.tri(A)] %in% c(4,9))

[1] 8

`-` 풀이 7,8의 오류 예

In [ ]:
a <- c(1,2,4,4,8)

In [ ]:
sum(!(outer(a,a)[upper.tri(outer(a,a))] %in% a**2))

[1] 6

- 여기서 $a^2$이 $2^2$,$4^2$을 통해서만 계산되는 것이 아닌 $1×4$, $2×8$ 등을 통해서도 나올 수 있음 -> $1×4$, $2×8$ 값이 제외될 수 있음

`-` 추가학습

In [ ]:
A %>% mutate(C=Var1-Var2) %>% filter(C > 0) %>% count %>% as.numeric

[1] 8